### ISSUE TITLE
Trenger AIS data

### ISSUE THREAD

**Issue by ellvtr** [GeoForum/veiledning04#1]
Trenger AIS data, se specs:
## ANIMASJON AV AIS-DATA I CARTODB
1. Bruke AIS-demodata (fås av meg) til å lage en animasjon ala denne: http://153.44.6.24/animation/OsloAnimation.html
2.  Ola Brandt i Kystverket (Brandt, Ola ola.brandt at kystverket.no) skal være kreditert i tutorial
3.  Beskrive stegene og mulighetene + fordelene med animasjoner
4.   Gjerne animere andre datasett fra de andre tutorialene også hvis det er trivielt.

**Comment by alexanno** [comment]
Vi snakket jo om dette på møte - men du fikk kanskje ikke med deg linken.. 
https://www.dropbox.com/s/4ft3el9qr4uqqfw/ais_20130829.geojson?dl=0

**Comment by ellvtr** [comment]
Takk, det hadde jeg glemt.
