### ISSUE TITLE
Time slider viser tall, ikke dato

### ISSUE THREAD

**Issue by ellvtr** [GeoForum/veiledning04#2]
Har prøvd diverse sql uten succes - se filen data01.sql.
![screenshot](https://cloud.githubusercontent.com/assets/12038749/7839293/ec07927a-0491-11e5-9c97-7e6f84e6fad8.png)

**Comment by ellvtr** [comment]
Denne tutorial viser et liknenende eksempel med dato på tidslinjen:
http://academy.cartodb.com/courses/01-beginners-course/lesson-4.html

**Comment by alexanno** [comment]
Du må ha en "date" kolonne i tabellen. Den kan lages dynamisk, men det beste er kanskje å ikke gjøre dette on-the-fly - fks ved å kjøre en UPDATE først. 

Denne funker for eksempel - men da kjører den on-the-fly

```
SELECT *, to_timestamp(date_time_utc::text,'YYYYMMDDHH24MISS') datokolonne FROM ais_20130829
```

**Comment by ellvtr** [comment]
Jeg ser at du har fikset dette i online-versjonen. Den viser nå klokkeslett. Lurer på hvordan man får den til å vise dato på tidslinjen.

**Comment by alexanno** [comment]
Det kommer kanskje opp hvis det er flere enn en dato i datasettet?
27. mai 2015 22.13 skrev "Jonas Ellehauge" notifications@github.com:

**Comment by ellvtr** [comment]
Ah, la ikke merke til at alle punkter er fra samme dato!
`select distinct substring(date_time_utc::text, 0,9) from ais_20130829`
gir et resultat.
